---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
            exclude: docs/
          - id: check-yaml
          - id: check-added-large-files
          - id: debug-statements
    - repo: https://github.com/ambv/black
      rev: 23.3.0
      hooks:
          - id: black
            args: [--safe, --quiet, --line-length, "100"]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.0.270
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.30.0
      hooks:
          - id: yamllint
