repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: docs/
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
-   repo: https://gitlab.com/pycqa/flake8.git
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--max-line-length, "100"]
        additional_dependencies: [flake8-docstrings]
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    -   id: black
        args: [--safe, --quiet, --line-length, "100"]
