---

- name: Setup and Configure Quipucords Components
  hosts: localhost
  vars:
      config_template: "./config-template.yaml"
      config_location: "~/.config/camayoc/config.yaml"
      server_ip: "127.0.0.1"
      container_ssh_file: "/sshkeys/id_rsa"
      isolated_fs: "~/quipucords/server/volumes/sshkeys/"
      sshkeyfile: "~/.ssh/id_rsa"
      volume_sshkeyfile: "~/quipucords/server/volumes/sshkeys/id_rsa"
      isolated_fs_user: "ryan"

  tasks:
    ## Need to Ensure/Make dir if does not exist
    - name: Copy config template to config location
      copy:
        src: "{{ config_template }}"
        dest: "{{ config_location }}"

    - name: Replace server IPs in config file
      replace:
        path: "{{ config_location }}"
        regexp: '{jenkins_slave_ip}'
        replace: "{{ server_ip }}"

        #    - name: Change sshkeys dir ownership
        #      file:
        #        path: "{{ isolated_fs }}"
        #        state: directory
        #        recurse: yes
        #        owner: "{{ isolated_fs_user }}"
        #        group: "{{ isolated_fs_user }}"


    - name: Change sshkeys dir ownership
      shell: "sudo chown -R {{ isolated_fs_user }}:{{ isolated_fs_user }} {{ isolated_fs }}"


    - name: Copy sshkeyfile to container volume
      copy:
        src: "{{ sshkeyfile }}"
        dest: "{{ volume_sshkeyfile }}"

        #    - name: Change volume sshkeyfile permission
        #      file:
        #        path: "{{ volume_sshkeyfile }}"
        #        mode: "0600"

    - name: Change volume sshkeyfile permission
      shell: "sudo chmod -R 0600 {{ volume_sshkeyfile }}"

    - name: Set container ssh location in config file
      replace:
        path: "{{ config_location }}"
        regexp: '{jenkins_ssh_file}'
        replace: "{{ container_ssh_file }}"

    - name: Set isolated_fs_placeholder in config file
      replace:
        path: "{{ config_location }}"
        regexp: '{isolated_fs_placeholder}'
        replace: "{{ isolated_fs }}"
