"""Web user interface reports view tests.

:caseautomation: automated
:casecomponent: ui
:caseimportance: medium
:caselevel: integration
:testtype: functional
"""

import tarfile

import pytest

from camayoc.config import settings
from camayoc.tests.qpc.utils import assert_ansible_logs
from camayoc.tests.qpc.utils import assert_lightspeed_report
from camayoc.tests.qpc.utils import assert_sha256sums
from camayoc.tests.qpc.utils import has_network_source
from camayoc.tests.qpc.utils import scan_should_have_lightspeed_report
from camayoc.ui import Client
from camayoc.ui import data_factories
from camayoc.ui.enums import MainMenuPages


def scan_names():
    for scan_definition in settings.scans:
        yield pytest.param(scan_definition.name)


@pytest.mark.pr_only
@pytest.mark.parametrize("scan_name", scan_names())
def test_download_report(tmp_path, scans, ui_client: Client, scan_name):
    """Download a report from the Reports view page.

    :id: 8cb1c417-2b2b-43aa-9f78-f6e1ecf16b65
    :description: Navigate to the Reports view page and download a report
        generated by a finished scan using the kebab action menu.
    :steps:
        1) Log into the UI.
        2) Navigate to the Reports page.
        3) Download the report for the finished scan.
        4) Verify downloaded file looks like a valid report.
        5) Log out.
    :expectedresults: Report is downloaded and valid. User is logged out.
    """
    finished_scan = scans.with_name(scan_name)
    (
        ui_client.begin()
        .login(data_factories.LoginFormDTOFactory())
        .navigate_to(MainMenuPages.REPORTS)
        .download_report(scan_name)
        .logout()
    )

    is_network_scan = has_network_source(scan_name)
    expect_lightspeed_report = scan_should_have_lightspeed_report(finished_scan)
    downloaded_report = ui_client.downloaded_files[-1]

    with tarfile.open(downloaded_report.path()) as archive:
        archive.extractall(tmp_path, filter="data")
    assert_sha256sums(tmp_path)
    assert_ansible_logs(tmp_path, is_network_scan)
    assert_lightspeed_report(tmp_path, expect_lightspeed_report)
