"""Web user interface reports view tests.

:caseautomation: automated
:casecomponent: ui
:caseimportance: medium
:caselevel: integration
:testtype: functional
"""

import tarfile

import pytest

from camayoc.config import settings
from camayoc.tests.qpc.utils import assert_sha256sums
from camayoc.ui import Client
from camayoc.ui import data_factories
from camayoc.ui.enums import MainMenuPages


def scan_names():
    for scan_definition in settings.scans:
        yield pytest.param(scan_definition.name)


@pytest.mark.pr_only
@pytest.mark.parametrize("scan_name", scan_names())
def test_reports_present(scans, ui_client: Client, scan_name):
    """Verify report from a finished scan is present on the Reports page.

    :id: 8a3c1e2f-5b7d-4a90-bc6e-1f2d3e4a5b6c
    :description: Navigate to the Reports view page and verify that
        a report generated by a finished scan is listed in the table.
    :steps:
        1) Log into the UI.
        2) Navigate to the Reports page.
        3) Verify a report with the expected scan name is present.
        4) Log out.
    :expectedresults: Report is found in the table. User is logged out.
    """
    scans.with_name(scan_name)
    (
        ui_client.begin()
        .login(data_factories.LoginFormDTOFactory())
        .navigate_to(MainMenuPages.REPORTS)
        .assert_report_present(scan_name)
        .logout()
    )


@pytest.mark.pr_only
@pytest.mark.parametrize("scan_name", scan_names())
def test_download_report(tmp_path, scans, ui_client: Client, scan_name):
    """Download a report from the Reports view page.

    :id: 7b4d2f1e-6c8a-4e91-ad7f-2g3e4f5a6b7d
    :description: Navigate to the Reports view page and download a report
        generated by a finished scan using the kebab action menu.
    :steps:
        1) Log into the UI.
        2) Navigate to the Reports page.
        3) Download the report for the finished scan.
        4) Verify downloaded file looks like a valid report.
        5) Log out.
    :expectedresults: Report is downloaded and valid. User is logged out.
    """
    scans.with_name(scan_name)
    (
        ui_client.begin()
        .login(data_factories.LoginFormDTOFactory())
        .navigate_to(MainMenuPages.REPORTS)
        .download_report(scan_name)
        .logout()
    )

    downloaded_report = ui_client.downloaded_files[-1]

    with tarfile.open(downloaded_report.path()) as archive:
        archive.extractall(tmp_path, filter="data")
    assert_sha256sums(tmp_path)
